{
 "title": "Infrastructure Overview",
 "panels": [
  {
   "title": "CPU Usage (%)",
   "type": "graph",
   "gridPos": { "x": 0, "y": 0, "w": 12, "h": 6 },
   "targets": [
    {
     "expr": "100 - (avg by(instance_name) (rate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "{{instance_name}}"
    }
   ]
  },
  {
   "title": "Memory Usage (%)",
   "type": "graph",
   "gridPos": { "x": 12, "y": 0, "w": 12, "h": 6 },
   "targets": [
    {
     "expr": "100 * (1 - (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes))",
     "legendFormat": "{{instance_name}}"
    }
   ]
  },
  {
   "title": "Frontend Requests (ALB)",
   "type": "graph",
   "gridPos": { "x": 0, "y": 6, "w": 12, "h": 6 },
   "targets": [
    {
     "expr": "round(increase(aws_applicationelb_request_count_sum[5m]))",
     "legendFormat": "{{load_balancer}}"
    }
   ]
  },
  {
   "title": "Infrastructure Costs (USD)",
   "type": "graph",
   "gridPos": { "x": 12, "y": 6, "w": 12, "h": 6 },
   "targets": [
    {
     "expr": "aws_billing_estimated_charges_maximum{currency=\"USD\"}",
     "legendFormat": "{{currency}}"
    }
   ]
  }
 ]
}